<a href="https://colab.research.google.com/github/Sriva29/applied-math-machine-learning/blob/main/Lab_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 1 </p>

In [3]:
# importing numpy
import numpy as np

In [8]:
# Create a numpy array with the elements "1, 2, 3, 5, 0", print the array and test if all of its elements are non-zero.
a = np.array([1,2,3,5,0])
print (a)
print ("Are all elements in array a non-zero?", a.all())

[1 2 3 5 0]
Are all elements in array a non-zero? False


In [ ]:
# Create a numpy array with the elements "3, -1, 3, 7, 2", print the array and test if any of its elements is non-zero.

In [9]:
b = np.array([3, -1, 3, 7, 2])
print(b)
print("Are any of the arrays in array b non-zero?", b.any())

[ 3 -1  3  7  2]
Are any of the arrays in array b non-zero? True


In [ ]:
# Create a numpy array with the elements "0, 0, 0, 0", print the array and test if any of its elements is non-zero.

In [10]:
c = np.array([0, 0, 0, 0])
print(c)
print("are any of the arrays of array c non-zero?", c.any())

[0 0 0 0]
are any of the arrays of array c non-zero? False


In [ ]:
# Create a numpy array with the elements "56, -2, 7", print the array and the amount of memory required to store it.

In [12]:
d = np.array([56, -2, 7])
print(d)
print("The amount of memory required to store array d is: ", d.itemsize*d.size)

[56 -2  7]
The amount of memory required to store array d is:  24


In [ ]:
# Create a numpy array with 10 zeros and print the array.

# Create a numpy array with 6 ones and print the array.

# Create a numpy array with 12 '3's and print the array. [3 3 3 3 3 3 3 3 3 3 3 3]


In [16]:
e = np.zeros(10)
print(e)
f = np.ones(6)
print(f)
g = np.ones(12)*3
print(g)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]


In [ ]:
# Create a numpy array of the integers from 8 to 20 and print the array. (make sure 20 itself is included) hint:  use "arange" method

# Create a numpy array of the even integers from 8 to 20 and print the array. (make sure 20 itself is included)   hint:  use "arange" method


In [ ]:
# Create a numpy array consisting of 100 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.

# Create a numpy array consisting of 1000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.

# Create a numpy array consisting of 1000000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.

# (Bonus question) Looking at the three above examples with 1000, 5000, and 10000 random elements, do you have any observations about mean and std values?
